import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { MouseEventHandler } from "react";
import Link from "next/link";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  let scrollSmootly = (
    event: any
  ): MouseEventHandler<HTMLAnchorElement> | undefined => {
    console.log(event);
    console.log("smooth");
    return undefined;
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container_main}>
        <div className="home" id="home">
          {/* <Header></Header> */}
          {/* <header>
            <nav>
              <h1>StreDko</h1>
              <ul>
                <li>
                  <Link href="#home">Domov</Link>
                </li>
                <li>
                  <Link href="#about">Kto sme?</Link>
                </li>
                <li>
                  <Link href="#events">Udalosti</Link>
                </li>
                <li>
                  <Link href="#contacts">Kontakt</Link>
                </li>
                <li>
                  <Link href="/login">Login</Link>
                </li>
              </ul>
            </nav>
          </header> */}
        </div>
        <main>
          <div className="about" id="about">
            <div className="info">
              <h2>Kto sme?</h2>
              <p>
                Sme vysokoškoláci a mladí pracujúci ľudia, ktorí sa stretávajú
                každú stredu (preto streDko, chápeš) počas školského roka
                <b> po omši o 18:45</b> na fare - oproti kostolu sv. Jindřicha a
                sv. Kunhuty.
              </p>
              <br />
              <p>
                Okrem pravidelných stretiek organizujeme aj iné akcie - duchovné
                obnovy, výlety, chodíme spolu na rôzne kultúrne podujatia,
                zašportovať si... alebo si ideme len tak sadnúť na pivo, burger.
              </p>
              <br />
              <p>Neváhaj, a príď nás niekedy pozrieť. :))</p>
            </div>
            <div className="img" id="img">
              <Image
                alt=""
                src={"/static/images/stredko.jpg"}
                width={700}
                height={700}
              ></Image>
            </div>
          </div>
          <div id="events">
            <h2>Udalosti</h2>
          </div>
        </main>
      </div>
    </>
  );
}
